### ISSUE TITLE
Cooking for Blockheads II book can't be crafted

### ISSUE THREAD

**Issue by FloppyDingo** [talonos2/BlightfallTracker#75] opened 2015-08-21 23:13 UTC
Crafting recipe is set to being a Cooking for Blockheads II book and a crafting table. I assume this is meant to be the first book and a crafting table. As is, this makes the book unobtainable.

**Comment by talonos2** [comment] 2015-08-22 00:04
Duplicate of #65.

**Closed as completed** 2015-08-22 00:04 UTC
Labels: duplicate, Fixed next version
