### ISSUE TITLE
Fail to Download Blightfall

### ISSUE THREAD

**Issue by pinkcat13** [talonos2/BlightfallTracker#140] opened 2015-09-23 19:08 UTC
When trying to download the 2.1.4 version of Blight fall I receive the following error message: 

Error downloading a file for the following pack: Blightfall
Failed to download http://mirror.technicpack.net/Technic/mods/commons-compress/commons-compress-v1.8.1-Copy.zip

This happens at 70 percent.  I have tried deleting the modpack and the technic launcher.  Neither has helped, I always receive the same message.  When starting the download of the pack, three line in the console show up red: 

SLF4J  Failed to load class “org.slf4j.impl.StaticLoggerBinder”.  
SLF4J  Defaulting to no-operation (NOP)  logger implementation 
SLF4J:  See Http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

And at 69 percent, the console shows this in red:
[B#319] java.net.SocketException: Unexpected end of file from server
[B#319]     at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
[B#319]     at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
[B#319]     at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
[B#319]     at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
[B#319]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[B#319]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[B#319]     at java.net.HttpURLConnection.getResponseCode(Unknown Source)
[B#319]     at net.technicpack.launchercore.mirror.download.Download.run(Download.java:70)
[B#319]     at net.technicpack.launchercore.mirror.MirrorStore.downloadFile(MirrorStore.java:116)
[B#319]     at net.technicpack.launchercore.install.tasks.DownloadFileTask.runTask(DownloadFileTask.java:57)
[B#319]     at net.technicpack.launchercore.install.tasks.TaskGroup.runTask(TaskGroup.java:86)
[B#319]     at net.technicpack.launchercore.install.InstallTasksQueue.runAllTasks(InstallTasksQueue.java:52)
[B#319]     at net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:42)
[B#319]     at net.technicpack.launcher.launch.Installer$1.run(Installer.java:116)
[B#319]     at java.lang.Thread.run(Unknown Source)
[B#319] Download of http://mirror.technicpack.net/Technic/mods/commons-compress/commons-compress-v1.8.1 - Copy.zip Failed!

It tries once more, with the same console issues, and then completely fails to download.  I really enjoyed playing this pack and hope this issue can be resolved soon.

**Comment by talonos2** [comment] 2015-10-03 00:16
Duplicate of #137

**Closed as completed by talonos2** 2015-10-03 00:16 UTC
