### ISSUE TITLE
Problem with title screen

### ISSUE THREAD

**Issue by ghost** [talonos2/BlightfallTracker#56] opened 2015-08-19 18:27 UTC
The pack opens fine, but when the title screen comes up, it just appears as a square in the corner with the rest of the screen being blank. Nothing crashes, but I cant do anything else past the square. Im not sure what the problem is.

**Comment by talonos2** [comment] 2015-08-19 18:59
Duplicate of #19. See that thread for details. TLDR: I'm afraid your graphics card is just really old, but you can fix it by manually editing the version json.

**Closed as completed** 2015-08-19 19:07 UTC
Labels: duplicate
