### ISSUE TITLE
Drop Pod teleports leave you stuck in the block below where you should be teleported

### ISSUE THREAD

**Issue by epicsupermonkey** [talonos2/BlightfallTracker#16] opened 2015-08-14 15:56 UTC
Every time I use a drop pod to go back up to the jaded I get half stuck in the block below me which my screen shakes like my player is bouncing up and down slightly but there is no way to get out due to the inability to break blocks on the jaded.

 I am not looking for a solution but I really like th eidea of this modpack and want to help bug report and see it grow. Thank you for the great mod and I look forward to see it grow.

**Comment by talonos2** [comment] 2015-08-16 22:44
Duplicate of issue #20 . Check there for my proposed temporary solution.

**Closed as completed** 2015-08-16 22:44 UTC
Labels: duplicate
