### ISSUE TITLE
Crash with search in NEI

### ISSUE THREAD

**Issue by JokarLP** [talonos2/BlightfallTracker#92] opened 2015-08-24 10:10 UTC
If you type "Ender" into the searchbar from NEI I will kicked from the server with this message:

A fatal error has occured, this connection is terminated

And in the console there is this Error: http://pastebin.com/x3Vw4Ew7 (Just ignore the time. I haven't setup the timezone yet).
If you then try to rejoin and open your inventory you will crash again. You must before delete the client config file from NEI. Please fix it

**Comment by talonos2** [comment] 2015-08-24 16:23
This is a known issue if you try and upgrade the forge version of
Blightfall. Blightfall's forge version is version-locked to preserve
compatibility with some older mods.

**Comment by talonos2** [comment] 2015-08-24 16:24
Duplicate of #14

**Closed as completed by talonos2** 2015-08-24 16:24 UTC

**Comment by JokarLP** [comment] 2015-08-24 16:26
So i must update the forge version?

**Comment by JokarLP** [comment] 2015-08-24 16:30
What must i do to fix. sorry. I'm german?

**Comment by talonos2** [comment] 2015-08-24 16:31
No, you must _UN_ upgrade it. Blightfall runs forge 1291. Any forge version
above 1355 will cause this crash. I have only ever seen this error when
people upgrade forge (which often happens accidentally when they try to use
Multi-MC, etc.)

**Comment by JokarLP** [comment] 2015-08-24 16:32
so i must install the forge version 1291?

**Comment by talonos2** [comment] 2015-08-24 16:35
Yes.

It should come pre-installed with the modpack when you download it from
technic. I'm honestly not sure how you got a different forge version.

But yes. Blightfall will not run reliably with any forge version except for
1291.

**Comment by JokarLP** [comment] 2015-08-24 16:36
i just install the Blightfall version 2.1.1a from the Technic Launcher with my friends and we all have this error

**Comment by JokarLP** [comment] 2015-08-24 16:37
this is the version who has the launcher installed: ForgeMultipart-1.7.10-1.1.1.321-universal

**Comment by JokarLP** [comment] 2015-08-24 16:51
will it works if i delete this file and replace them with "forge-1.7.10-10.13.2.1291-universal.jar"

**Comment by JokarLP** [comment] 2015-08-24 16:51
or will he try to reinstall "ForgeMultipart-1.7.10-1.1.1.321-universal.jar"

**Comment by talonos2** [comment] 2015-08-24 17:06
No. Forge Multipart is not Forge.

Are you running this straight from the technic launcher? Or are you using
some other launcher, like Multi-MC?

**Comment by JokarLP** [comment] 2015-08-24 17:06
straight from the technic launcher

**Comment by talonos2** [comment] 2015-08-24 17:13
In that case, I'd suggest deleting and re-installing the pack.

**Comment by JokarLP** [comment] 2015-08-24 17:14
okay. after that i must reinstall it right?

**Comment by JokarLP** [comment] 2015-08-24 17:15
And musst i then reinstall the server? there is also the ForgeMultipart

**Comment by talonos2** [comment] 2015-08-24 17:17
Forge multipart is meant to be on version 1.1.1.321. It's fine.

Before trying to install the server, make sure it works in single player.
After that, yes, just unzip a fresh copy of the server downloaded from the
technic site.

**Comment by JokarLP** [comment] 2015-08-24 17:19
Is it already updated/reinstalled?

**Comment by JokarLP** [comment] 2015-08-25 10:00
So could i now reinstall the package to fix the problem?

**Comment by JokarLP** [comment] 2015-08-25 11:30
I have now tried to use the version 2.1.2 and on single player there is no crash while the serach in NEi but if i want to leave the singleplayer world the game closed. and the problem is still on the server. i have the server also updated to 2.1.2 but the problem isn't fix

**Comment by JokarLP** [comment] 2015-08-26 16:14
What should i do. i have the problem with 2.1.2 too
