### ISSUE TITLE
Can't download commons compress

### ISSUE THREAD

**Issue by MrAlaboheme** [talonos2/BlightfallTracker#137] opened 2015-09-22 05:43 UTC
Hi,
When i want to download the modpack, it crash when the game want to download the mod commons compress. So i can't finish to install it. Is some link are dead ? Maybe check for this one particularly.

Thanks you. :)

**Comment by talonos2** [comment] 2015-10-03 00:26
Duplicate of #133

**Closed as completed by talonos2** 2015-10-03 00:26 UTC
