### ISSUE TITLE
Transporter beacons reset

### ISSUE THREAD

**Issue by zitcream** [talonos2/BlightfallTracker#26] opened 2015-08-15 21:23 UTC
After saving and quitting the game and logging back in again, all the warp points in the transporter beacon have been reset. Thankfully, I only had 2 or 3 locations set so it was ok, but now I don't want to do the scouting missions.

**Comment by zitcream** [comment] 2015-08-15 21:34
Upon further inspection, the materials books are also reset, but I don't use them anyway

**Comment by talonos2** [comment] 2015-08-17 00:51
Warp points resetting upon quitting the game is not something I have been able to reproduce.

Warp data is based on your character's name. I don't suppose you logged out as one character, then loaded the save file as a different minecraft account? That would explain it.

**Comment by zitcream** [comment] 2015-08-18 16:20
I use the same username, and it does save the points whenh I close the game and open it again until I restart the technic launcher, which resets them.

**Comment by zitcream** [comment] 2015-08-18 16:23
I use the same username, and the warp points are saved when I restart the game, but when I restart the launcher, it all screws up. Also, if it was username based, wouldn't my inventory be cleared?

PS: I accidentally clicked the close and comment button instead of the comment button :P

**Comment by talonos2** [comment] 2015-09-09 17:46
If anybody else has this happen to them, let me know. Until then, this is closed as "Cannot reproduce."

**Closed as completed by talonos2** 2015-09-09 17:46 UTC
Labels: Cannot Reproduce
