### ISSUE TITLE
load screen error/bug (unplayable)

### ISSUE THREAD

**Issue by niko19900** [talonos2/BlightfallTracker#124] opened 2015-09-10 02:19 UTC
![error](https://cloud.githubusercontent.com/assets/14209761/9778607/b34de46e-5740-11e5-9024-1a21d96ef93b.png)
so the modpack loads up and i end up with this any ideas?

**Comment by talonos2** [comment] 2015-09-10 02:32
Duplicate of #19. See bochen415's comment at the bottom for the fix.

**Closed as completed by talonos2** 2015-09-10 02:32 UTC
Labels: duplicate
