### ISSUE TITLE
Ender NEI crash

### ISSUE THREAD

**Issue by JokarLP** [talonos2/BlightfallTracker#106] opened 2015-08-27 10:06 UTC
I know its a duplicate from #14 and #92 but you talonos2 hasn't answer me anymore at #92 
I need really your help. You sayed you would reinstall the packet. I has updated to version 2.1.2 and the problem still exists. I does have seen some server they has fix it but i have no way how to fix it found on the web without updating the ChickenBones mods that i must also update on my client to play. but how could some server fix the problem without this. Please help

**Comment by talonos2** [comment] 2015-09-09 18:36
Self-Proclaimed duplicate of #92. Fixed elsewhere.

**Closed as completed by talonos2** 2015-09-09 18:36 UTC
Labels: invalid
